
import { Category, AvatarConfig } from './types';

export const AVATARS: AvatarConfig[] = [
  { id: 'leo', name: 'Leo', emoji: '🦁', color: 'bg-orange-400', description: 'Brave & Fun' },
  { id: 'mimi', name: 'Mimi', emoji: '🧚', color: 'bg-pink-400', description: 'Kind & Magic' },
  { id: 'bot', name: 'Bot', emoji: '🤖', color: 'bg-blue-400', description: 'Smart & Cool' }
];

export const CATEGORIES: Category[] = [
  { id: 'animals', name: 'Animals', icon: '🦁', color: 'bg-orange-400', items: [
    { id: 'a1', name: 'Lion', persianName: 'شیر', emoji: '🦁', color: 'orange' },
    { id: 'a2', name: 'Elephant', persianName: 'فیل', emoji: '🐘', color: 'gray' },
    { id: 'a3', name: 'Giraffe', persianName: 'زرافه', emoji: '🦒', color: 'yellow' },
    { id: 'a4', name: 'Monkey', persianName: 'میمون', emoji: '🐒', color: 'brown' },
    { id: 'a5', name: 'Tiger', persianName: 'ببر', emoji: '🐯', color: 'orange' },
    { id: 'a6', name: 'Zebra', persianName: 'گورخر', emoji: '🦓', color: 'white' },
    { id: 'a7', name: 'Rabbit', persianName: 'خرگوش', emoji: '🐰', color: 'white' },
    { id: 'a8', name: 'Cat', persianName: 'گربه', emoji: '🐱', color: 'gray' },
    { id: 'a9', name: 'Dog', persianName: 'سگ', emoji: '🐶', color: 'brown' },
    { id: 'a10', name: 'Bear', persianName: 'خرس', emoji: '🐻', color: 'brown' },
    { id: 'a11', name: 'Panda', persianName: 'پاندا', emoji: '🐼', color: 'black' },
    { id: 'a12', name: 'Kangaroo', persianName: 'کانگورو', emoji: '🦘', color: 'brown' },
    { id: 'a13', name: 'Wolf', persianName: 'گرگ', emoji: '🐺', color: 'gray' },
    { id: 'a14', name: 'Fox', persianName: 'روباه', emoji: '🦊', color: 'orange' },
    { id: 'a15', name: 'Horse', persianName: 'اسب', emoji: '🐴', color: 'brown' },
    { id: 'a16', name: 'Cow', persianName: 'گاو', emoji: '🐮', color: 'white' },
    { id: 'a17', name: 'Pig', persianName: 'خوک', emoji: '🐷', color: 'pink' },
    { id: 'a18', name: 'Sheep', persianName: 'گوسفند', emoji: '🐑', color: 'white' },
    { id: 'a19', name: 'Goat', persianName: 'بز', emoji: '🐐', color: 'gray' },
    { id: 'a20', name: 'Deer', persianName: 'آهو', emoji: '🦌', color: 'brown' }
  ]},
  { id: 'fruits', name: 'Fruits', icon: '🍎', color: 'bg-red-400', items: [
    { id: 'f1', name: 'Apple', persianName: 'سیب', emoji: '🍎', color: 'red' },
    { id: 'f2', name: 'Banana', persianName: 'موز', emoji: '🍌', color: 'yellow' },
    { id: 'f3', name: 'Orange', persianName: 'پرتقال', emoji: '🍊', color: 'orange' },
    { id: 'f4', name: 'Strawberry', persianName: 'توت فرنگی', emoji: '🍓', color: 'red' },
    { id: 'f5', name: 'Grapes', persianName: 'انگور', emoji: '🍇', color: 'purple' },
    { id: 'f6', name: 'Watermelon', persianName: 'هندوانه', emoji: '🍉', color: 'red' },
    { id: 'f7', name: 'Pineapple', persianName: 'آناناس', emoji: '🍍', color: 'yellow' },
    { id: 'f8', name: 'Mango', persianName: 'انبه', emoji: '🥭', color: 'orange' },
    { id: 'f9', name: 'Cherry', persianName: 'گیلاس', emoji: '🍒', color: 'red' },
    { id: 'f10', name: 'Peach', persianName: 'هلو', emoji: '🍑', color: 'pink' },
    { id: 'f11', name: 'Pear', persianName: 'گلابی', emoji: '🍐', color: 'green' },
    { id: 'f12', name: 'Kiwi', persianName: 'کیوی', emoji: '🥝', color: 'green' },
    { id: 'f13', name: 'Lemon', persianName: 'لیمو', emoji: '🍋', color: 'yellow' },
    { id: 'f14', name: 'Coconut', persianName: 'نارگیل', emoji: '🥥', color: 'brown' },
    { id: 'f15', name: 'Melon', persianName: 'طالبی', emoji: '🍈', color: 'green' },
    { id: 'f16', name: 'Blueberry', persianName: 'تمشک آبی', emoji: '🫐', color: 'blue' },
    { id: 'f17', name: 'Avocado', persianName: 'آووکادو', emoji: '🥑', color: 'green' },
    { id: 'f18', name: 'Pomegranate', persianName: 'انار', emoji: '🍅', color: 'red' },
    { id: 'f19', name: 'Apricot', persianName: 'زردآلو', emoji: '🍑', color: 'orange' },
    { id: 'f20', name: 'Fig', persianName: 'انجیر', emoji: '🥯', color: 'purple' }
  ]},
  { id: 'numbers', name: 'Numbers', icon: '🔢', color: 'bg-blue-400', items: [
    'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
    'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen', 'Twenty'
  ].map((name, i) => {
    const numValue = i + 1;
    const displayEmoji = numValue <= 10 ? (numValue === 10 ? "🔟" : `${numValue}️⃣`) : numValue.toString();
    
    return {
      id: `n${numValue}`, 
      name: name,
      persianName: ['یک','دو','سه','چهار','پنج','شش','هفت','هشت','نه','ده','یازده','دوازده','سیزده','چهارده','پانزده','شانزده','هفده','هجده','نوزده','بیست'][i], 
      emoji: displayEmoji, 
      color: 'blue'
    };
  })},
  { id: 'vehicles', name: 'Vehicles', icon: '🚗', color: 'bg-slate-500', items: [
    { id: 'v1', name: 'Car', persianName: 'ماشین', emoji: '🚗', color: 'red' },
    { id: 'v2', name: 'Bus', persianName: 'اتوبوس', emoji: '🚌', color: 'yellow' },
    { id: 'v3', name: 'Truck', persianName: 'کامیون', emoji: '🚚', color: 'blue' },
    { id: 'v4', name: 'Plane', persianName: 'هواپیما', emoji: '✈️', color: 'white' },
    { id: 'v5', name: 'Train', persianName: 'قطار', emoji: '🚂', color: 'green' },
    { id: 'v6', name: 'Rocket', persianName: 'موشک', emoji: '🚀', color: 'red' },
    { id: 'v7', name: 'Ship', persianName: 'کشتی', emoji: '🚢', color: 'blue' },
    { id: 'v8', name: 'Bicycle', persianName: 'دوچرخه', emoji: '🚲', color: 'silver' },
    { id: 'v9', name: 'Motorcycle', persianName: 'موتورسیکلت', emoji: '🏍️', color: 'black' },
    { id: 'v10', name: 'Helicopter', persianName: 'هلیکوپتر', emoji: '🚁', color: 'red' },
    { id: 'v11', name: 'Submarine', persianName: 'زیردریایی', emoji: '🚤', color: 'yellow' },
    { id: 'v12', name: 'Ambulance', persianName: 'آمبولانس', emoji: '🚑', color: 'white' },
    { id: 'v13', name: 'Police Car', persianName: 'ماشین پلیس', emoji: '🚓', color: 'blue' },
    { id: 'v14', name: 'Fire Truck', persianName: 'ماشین آتش‌نشانی', emoji: '🚒', color: 'red' },
    { id: 'v15', name: 'Taxi', persianName: 'تاکسی', emoji: '🚕', color: 'yellow' },
    { id: 'v16', name: 'Tractor', persianName: 'تراکتور', emoji: '🚜', color: 'green' },
    { id: 'v17', name: 'Scooter', persianName: 'اسکوتر', emoji: '🛴', color: 'orange' },
    { id: 'v18', name: 'Hot Air Balloon', persianName: 'بالون', emoji: '🎈', color: 'red' },
    { id: 'v19', name: 'Van', persianName: 'ون', emoji: '🚐', color: 'white' },
    { id: 'v20', name: 'Jeep', persianName: 'جیپ', emoji: '🚙', color: 'blue' }
  ]},
  { id: 'colors', name: 'Colors', icon: '🎨', color: 'bg-purple-400', items: [
    { id: 'c1', name: 'Red', persianName: 'قرمز', emoji: '🔴', color: 'red' },
    { id: 'c2', name: 'Blue', persianName: 'آبی', emoji: '🔵', color: 'blue' },
    { id: 'c3', name: 'Green', persianName: 'سبز', emoji: '🟢', color: 'green' },
    { id: 'c4', name: 'Yellow', persianName: 'زرد', emoji: '🟡', color: 'yellow' },
    { id: 'c5', name: 'Orange', persianName: 'نارنجی', emoji: '🟠', color: 'orange' },
    { id: 'c6', name: 'Purple', persianName: 'بنفش', emoji: '🟣', color: 'purple' },
    { id: 'c7', name: 'Pink', persianName: 'صورتی', emoji: '🌸', color: 'pink' },
    { id: 'c8', name: 'Brown', persianName: 'قهوه‌ای', emoji: '🟤', color: 'brown' },
    { id: 'c9', name: 'Black', persianName: 'سیاه', emoji: '⚫', color: 'black' },
    { id: 'c10', name: 'White', persianName: 'سفید', emoji: '⚪', color: 'white' },
    { id: 'c11', name: 'Gray', persianName: 'خاکستری', emoji: '🔘', color: 'gray' },
    { id: 'c12', name: 'Gold', persianName: 'طلایی', emoji: '🟡', color: 'gold' },
    { id: 'c13', name: 'Silver', persianName: 'نقره‌ای', emoji: '⚪', color: 'silver' },
    { id: 'c14', name: 'Cyan', persianName: 'فیروزه‌ای', emoji: '💎', color: 'cyan' },
    { id: 'c15', name: 'Lime', persianName: 'لیمویی', emoji: '🍋', color: 'lime' },
    { id: 'c16', name: 'Magenta', persianName: 'سرخابی', emoji: '🌺', color: 'magenta' },
    { id: 'c17', name: 'Maroon', persianName: 'زرشکی', emoji: '🍎', color: 'maroon' },
    { id: 'c18', name: 'Navy', persianName: 'سرمه‌ای', emoji: '🌌', color: 'navy' },
    { id: 'c19', name: 'Olive', persianName: 'زیتونی', emoji: '🫒', color: 'olive' },
    { id: 'c20', name: 'Rainbow', persianName: 'رنگین‌کمان', emoji: '🌈', color: 'multi' }
  ]},
  { id: 'space', name: 'Space', icon: '🚀', color: 'bg-indigo-900', items: [
    { id: 's1', name: 'Moon', persianName: 'ماه', emoji: '🌙', color: 'yellow' },
    { id: 's2', name: 'Sun', persianName: 'خورشید', emoji: '☀️', color: 'orange' },
    { id: 's3', name: 'Earth', persianName: 'زمین', emoji: '🌍', color: 'blue' },
    { id: 's4', name: 'Star', persianName: 'ستاره', emoji: '⭐', color: 'yellow' },
    { id: 's5', name: 'Rocket', persianName: 'موشک', emoji: '🚀', color: 'red' },
    { id: 's6', name: 'Planet', persianName: 'سیاره', emoji: '🪐', color: 'brown' },
    { id: 's7', name: 'Astronaut', persianName: 'فضانورد', emoji: '👨‍🚀', color: 'white' },
    { id: 's8', name: 'Alien', persianName: 'آدم فضایی', emoji: '👽', color: 'green' },
    { id: 's9', name: 'UFO', persianName: 'بشقاب پرنده', emoji: '🛸', color: 'silver' },
    { id: 's10', name: 'Telescope', persianName: 'تلسکوپ', emoji: '🔭', color: 'gray' },
    { id: 's11', name: 'Satellite', persianName: 'ماهواره', emoji: '🛰️', color: 'gray' },
    { id: 's12', name: 'Meteor', persianName: 'شهاب سنگ', emoji: '☄️', color: 'orange' },
    { id: 's13', name: 'Galaxy', persianName: 'کهکشان', emoji: '🌌', color: 'purple' },
    { id: 's14', name: 'Mars', persianName: 'مریخ', emoji: '🔴', color: 'red' },
    { id: 's15', name: 'Jupiter', persianName: 'مشتری', emoji: '🟠', color: 'brown' },
    { id: 's16', name: 'Saturn', persianName: 'زحل', emoji: '🪐', color: 'yellow' },
    { id: 's17', name: 'Black Hole', persianName: 'سیاه‌چاله', emoji: '🕳️', color: 'black' },
    { id: 's18', name: 'Comet', persianName: 'دنباله‌دار', emoji: '💫', color: 'yellow' },
    { id: 's19', name: 'Sky', persianName: 'آسمان', emoji: '☁️', color: 'blue' },
    { id: 's20', name: 'Night', persianName: 'شب', emoji: '🌃', color: 'navy' }
  ]},
  { id: 'jobs', name: 'Jobs', icon: '👨‍⚕️', color: 'bg-teal-500', items: [
    { id: 'j1', name: 'Doctor', persianName: 'دکتر', emoji: '👨‍⚕️', color: 'blue' },
    { id: 'j2', name: 'Nurse', persianName: 'پرستار', emoji: '👩‍⚕️', color: 'white' },
    { id: 'j3', name: 'Chef', persianName: 'آشپز', emoji: '👨‍🍳', color: 'white' },
    { id: 'j4', name: 'Teacher', persianName: 'معلم', emoji: '👩‍🏫', color: 'brown' },
    { id: 'j5', name: 'Pilot', persianName: 'خلبان', emoji: '👨‍✈️', color: 'blue' },
    { id: 'j6', name: 'Firefighter', persianName: 'آتشنشان', emoji: '👨‍🚒', color: 'red' },
    { id: 'j7', name: 'Police', persianName: 'پلیس', emoji: '👮', color: 'blue' },
    { id: 'j8', name: 'Artist', persianName: 'هنرمند', emoji: '🧑‍🎨', color: 'multi' },
    { id: 'j9', name: 'Singer', persianName: 'خواننده', emoji: '🧑‍🎤', color: 'purple' },
    { id: 'j10', name: 'Farmer', persianName: 'کشاورز', emoji: '👨‍🌾', color: 'brown' },
    { id: 'j11', name: 'Builder', persianName: 'بنا', emoji: '👷', color: 'yellow' },
    { id: 'j12', name: 'Dentist', persianName: 'دندانپزشک', emoji: '🦷', color: 'white' },
    { id: 'j13', name: 'Astronaut', persianName: 'فضانورد', emoji: '👨‍🚀', color: 'white' },
    { id: 'j14', name: 'Scientist', persianName: 'دانشمند', emoji: '🧑‍🔬', color: 'white' },
    { id: 'j15', name: 'Baker', persianName: 'نانوا', emoji: '🥖', color: 'brown' },
    { id: 'j16', name: 'Soldier', persianName: 'سرباز', emoji: '💂', color: 'green' },
    { id: 'j17', name: 'Writer', persianName: 'نویسنده', emoji: '✍️', color: 'black' },
    { id: 'j18', name: 'Photographer', persianName: 'عکاس', emoji: '📷', color: 'black' },
    { id: 'j19', name: 'Plumber', persianName: 'لوله‌کش', emoji: '🔧', color: 'gray' },
    { id: 'j20', name: 'Gardener', persianName: 'باغبان', emoji: '🪴', color: 'green' }
  ]},
  { id: 'body', name: 'Body', icon: '👂', color: 'bg-pink-300', items: [
    { id: 'b1', name: 'Eye', persianName: 'چشم', emoji: '👁️', color: 'blue' },
    { id: 'b2', name: 'Ear', persianName: 'گوش', emoji: '👂', color: 'peach' },
    { id: 'b3', name: 'Nose', persianName: 'بینی', emoji: '👃', color: 'peach' },
    { id: 'b4', name: 'Mouth', persianName: 'دهان', emoji: '👄', color: 'red' },
    { id: 'b5', name: 'Hand', persianName: 'دست', emoji: '🖐️', color: 'peach' },
    { id: 'b6', name: 'Foot', persianName: 'پا', emoji: '🦶', color: 'peach' },
    { id: 'b7', name: 'Head', persianName: 'سر', emoji: '👤', color: 'peach' },
    { id: 'b8', name: 'Hair', persianName: 'مو', emoji: '💇', color: 'black' },
    { id: 'b9', name: 'Finger', persianName: 'انگشت', emoji: '☝️', color: 'peach' },
    { id: 'b10', name: 'Tooth', persianName: 'دندان', emoji: '🦷', color: 'white' },
    { id: 'b11', name: 'Arm', persianName: 'بازو', emoji: '💪', color: 'peach' },
    { id: 'b12', name: 'Leg', persianName: 'ساق پا', emoji: '🦵', color: 'peach' },
    { id: 'b13', name: 'Back', persianName: 'کمر', emoji: '🚶', color: 'peach' },
    { id: 'b14', name: 'Knee', persianName: 'زانو', emoji: '🦵', color: 'peach' },
    { id: 'b15', name: 'Shoulder', persianName: 'شانه', emoji: '👤', color: 'peach' },
    { id: 'b16', name: 'Tongue', persianName: 'زبان', emoji: '👅', color: 'red' },
    { id: 'b17', name: 'Lips', persianName: 'لب', emoji: '👄', color: 'red' },
    { id: 'b18', name: 'Thumb', persianName: 'شست', emoji: '👍', color: 'peach' },
    { id: 'b19', name: 'Brain', persianName: 'مغز', emoji: '🧠', color: 'pink' },
    { id: 'b20', name: 'Heart', persianName: 'قلب', emoji: '❤️', color: 'red' }
  ]},
  { id: 'nature', name: 'Nature', icon: '🌲', color: 'bg-green-600', items: [
    { id: 'na1', name: 'Tree', persianName: 'درخت', emoji: '🌳', color: 'green' },
    { id: 'na2', name: 'Flower', persianName: 'گل', emoji: '🌸', color: 'pink' },
    { id: 'na3', name: 'Mountain', persianName: 'کوه', emoji: '⛰️', color: 'gray' },
    { id: 'na4', name: 'River', persianName: 'رودخانه', emoji: '🏞️', color: 'blue' },
    { id: 'na5', name: 'Sun', persianName: 'خورشید', emoji: '☀️', color: 'orange' },
    { id: 'na6', name: 'Grass', persianName: 'چمن', emoji: '🌿', color: 'green' },
    { id: 'na7', name: 'Rock', persianName: 'سنگ', emoji: '🪨', color: 'gray' },
    { id: 'na8', name: 'Leaf', persianName: 'برگ', emoji: '🍃', color: 'green' },
    { id: 'na9', name: 'Forest', persianName: 'جنگل', emoji: '🌲', color: 'green' },
    { id: 'na10', name: 'Sea', persianName: 'دریا', emoji: '🌊', color: 'blue' },
    { id: 'na11', name: 'Rainbow', persianName: 'رنگین‌کمان', emoji: '🌈', color: 'multi' },
    { id: 'na12', name: 'Waterfall', persianName: 'آبشار', emoji: '⛲', color: 'blue' },
    { id: 'na13', name: 'Sand', persianName: 'شن', emoji: '🏖️', color: 'yellow' },
    { id: 'na14', name: 'Wind', persianName: 'باد', emoji: '💨', color: 'gray' },
    { id: 'na15', name: 'Mushroom', persianName: 'قارچ', emoji: '🍄', color: 'red' },
    { id: 'na16', name: 'Bush', persianName: 'بوته', emoji: '🪴', color: 'green' },
    { id: 'na17', name: 'Lake', persianName: 'دریاچه', emoji: '🗾', color: 'blue' },
    { id: 'na18', name: 'Volcano', persianName: 'آتشفشان', emoji: '🌋', color: 'red' },
    { id: 'na19', name: 'Island', persianName: 'جزیره', emoji: '🏝️', color: 'green' },
    { id: 'na20', name: 'Cave', persianName: 'غار', emoji: '🛖', color: 'brown' }
  ]},
  { id: 'weather', name: 'Weather', icon: '☁️', color: 'bg-sky-400', items: [
    { id: 'w1', name: 'Sunny', persianName: 'آفتابی', emoji: '☀️', color: 'yellow' },
    { id: 'w2', name: 'Cloudy', persianName: 'ابری', emoji: '☁️', color: 'gray' },
    { id: 'w3', name: 'Rainy', persianName: 'بارانی', emoji: '🌧️', color: 'blue' },
    { id: 'w4', name: 'Snowy', persianName: 'برفی', emoji: '❄️', color: 'white' },
    { id: 'w5', name: 'Stormy', persianName: 'طوفانی', emoji: '⛈️', color: 'dark' },
    { id: 'w6', name: 'Windy', persianName: 'بادی', emoji: '💨', color: 'gray' },
    { id: 'w7', name: 'Thunder', persianName: 'رعد', emoji: '⚡', color: 'yellow' },
    { id: 'w8', name: 'Foggy', persianName: 'مه‌آلود', emoji: '🌫️', color: 'gray' },
    { id: 'w9', name: 'Hot', persianName: 'داغ', emoji: '🔥', color: 'red' },
    { id: 'w10', name: 'Cold', persianName: 'سرد', emoji: '🥶', color: 'blue' },
    { id: 'w11', name: 'Umbrella', persianName: 'چتر', emoji: '☂️', color: 'purple' },
    { id: 'w12', name: 'Snowman', persianName: 'آدم برفی', emoji: '☃️', color: 'white' },
    { id: 'w13', name: 'Lightning', persianName: 'صاعقه', emoji: '⚡', color: 'yellow' },
    { id: 'w14', name: 'Tornado', persianName: 'گردباد', emoji: '🌪️', color: 'gray' },
    { id: 'w15', name: 'Rainbow', persianName: 'رنگین‌کمان', emoji: '🌈', color: 'multi' },
    { id: 'w16', name: 'Degree', persianName: 'درجه', emoji: '🌡️', color: 'red' },
    { id: 'w17', name: 'Humidity', persianName: 'رطوبت', emoji: '💧', color: 'blue' },
    { id: 'w18', name: 'Moon', persianName: 'ماه', emoji: '🌙', color: 'yellow' },
    { id: 'w19', name: 'Stars', persianName: 'ستاره‌ها', emoji: '✨', color: 'yellow' },
    { id: 'w20', name: 'Sky', persianName: 'آسمان', emoji: '🌌', color: 'blue' }
  ]},
  { id: 'food', name: 'Food', icon: '🍕', color: 'bg-yellow-600', items: [
    { id: 'fo1', name: 'Pizza', persianName: 'پیتزا', emoji: '🍕', color: 'orange' },
    { id: 'fo2', name: 'Burger', persianName: 'همبرگر', emoji: '🍔', color: 'brown' },
    { id: 'fo3', name: 'Sandwich', persianName: 'ساندویچ', emoji: '🥪', color: 'brown' },
    { id: 'fo4', name: 'Cake', persianName: 'کیک', emoji: '🍰', color: 'pink' },
    { id: 'fo5', name: 'Ice Cream', persianName: 'بستنی', emoji: '🍦', color: 'white' },
    { id: 'fo6', name: 'Donut', persianName: 'پیراشکی', emoji: '🍩', color: 'brown' },
    { id: 'fo7', name: 'Chocolate', persianName: 'شکلات', emoji: '🍫', color: 'brown' },
    { id: 'fo8', name: 'Egg', persianName: 'تخم‌مرغ', emoji: '🥚', color: 'white' },
    { id: 'fo9', name: 'Milk', persianName: 'شیر', emoji: '🥛', color: 'white' },
    { id: 'fo10', name: 'Bread', persianName: 'نان', emoji: '🍞', color: 'brown' },
    { id: 'fo11', name: 'Soup', persianName: 'سوپ', emoji: '🍲', color: 'orange' },
    { id: 'fo12', name: 'Rice', persianName: 'برنج', emoji: '🍚', color: 'white' },
    { id: 'fo13', name: 'Spaghetti', persianName: 'اسپاگتی', emoji: '🍝', color: 'yellow' },
    { id: 'fo14', name: 'Cheese', persianName: 'پنیر', emoji: '🧀', color: 'yellow' },
    { id: 'fo15', name: 'Honey', persianName: 'عسل', emoji: '🍯', color: 'yellow' },
    { id: 'fo16', name: 'Popcorn', persianName: 'پاپ‌کورن', emoji: '🍿', color: 'white' },
    { id: 'fo17', name: 'Candy', persianName: 'آب‌نبات', emoji: '🍬', color: 'pink' },
    { id: 'fo18', name: 'Cookie', persianName: 'کلوچه', emoji: '🍪', color: 'brown' },
    { id: 'fo19', name: 'Juice', persianName: 'آبمیوه', emoji: '🧃', color: 'green' },
    { id: 'fo20', name: 'Meat', persianName: 'گوشت', emoji: '🥩', color: 'red' }
  ]},
  { id: 'toys', name: 'Toys', icon: '🧸', color: 'bg-rose-400', items: [
    { id: 't1', name: 'Teddy Bear', persianName: 'خرس پولیشی', emoji: '🧸', color: 'brown' },
    { id: 't2', name: 'Ball', persianName: 'توپ', emoji: '⚽', color: 'white' },
    { id: 't3', name: 'Doll', persianName: 'عروسک', emoji: '🪆', color: 'pink' },
    { id: 't4', name: 'Lego', persianName: 'لگو', emoji: '🧱', color: 'red' },
    { id: 't5', name: 'Car', persianName: 'ماشین', emoji: '🏎️', color: 'red' },
    { id: 't6', name: 'Train', persianName: 'قطار', emoji: '🚂', color: 'black' },
    { id: 't7', name: 'Robot', persianName: 'ربات', emoji: '🤖', color: 'gray' },
    { id: 't8', name: 'Kite', persianName: 'بادبادک', emoji: '🪁', color: 'purple' },
    { id: 't9', name: 'Puzzle', persianName: 'پازل', emoji: '🧩', color: 'multi' },
    { id: 't10', name: 'Balloon', persianName: 'بادکنک', emoji: '🎈', color: 'red' },
    { id: 't11', name: 'Blocks', persianName: 'مکعب‌ها', emoji: '📦', color: 'brown' },
    { id: 't12', name: 'Rocket', persianName: 'موشک', emoji: '🚀', color: 'white' },
    { id: 't13', name: 'Slide', persianName: 'سرسره', emoji: '🛝', color: 'blue' },
    { id: 't14', name: 'Swing', persianName: 'تاب', emoji: '🎡', color: 'green' },
    { id: 't15', name: 'Bicycle', persianName: 'دوچرخه', emoji: '🚲', color: 'blue' },
    { id: 't16', name: 'Skateboard', persianName: 'اسکیت برد', emoji: '🛹', color: 'black' },
    { id: 't17', name: 'Drum', persianName: 'طبل', emoji: '🥁', color: 'red' },
    { id: 't18', name: 'Yoyo', persianName: 'یویو', emoji: '🪀', color: 'green' },
    { id: 't19', name: 'Dice', persianName: 'تاس', emoji: '🎲', color: 'white' },
    { id: 't20', name: 'Crown', persianName: 'تاج', emoji: '👑', color: 'gold' }
  ]},
  { id: 'school', name: 'School', icon: '🎒', color: 'bg-blue-700', items: [
    { id: 'sc1', name: 'Book', persianName: 'کتاب', emoji: '📖', color: 'red' },
    { id: 'sc2', name: 'Pencil', persianName: 'مداد', emoji: '✏️', color: 'yellow' },
    { id: 'sc3', name: 'Backpack', persianName: 'کوله پشتی', emoji: '🎒', color: 'blue' },
    { id: 'sc4', name: 'Ruler', persianName: 'خط‌کش', emoji: '📏', color: 'yellow' },
    { id: 'sc5', name: 'Eraser', persianName: 'پاک‌کن', emoji: '🧼', color: 'pink' },
    { id: 'sc6', name: 'Paper', persianName: 'کاغذ', emoji: '📄', color: 'white' },
    { id: 'sc7', name: 'Crayons', persianName: 'مداد شمعی', emoji: '🖍️', color: 'multi' },
    { id: 'sc8', name: 'Notebook', persianName: 'دفتر', emoji: '📓', color: 'black' },
    { id: 'sc9', name: 'Teacher', persianName: 'معلم', emoji: '👩‍🏫', color: 'brown' },
    { id: 'sc10', name: 'Student', persianName: 'دانش‌آموز', emoji: '🧑‍🎓', color: 'black' },
    { id: 'sc11', name: 'Desk', persianName: 'میز', emoji: '🪑', color: 'brown' },
    { id: 'sc12', name: 'Clock', persianName: 'ساعت', emoji: '⏰', color: 'red' },
    { id: 'sc13', name: 'Globe', persianName: 'کره زمین', emoji: '🌍', color: 'blue' },
    { id: 'sc14', name: 'Scissors', persianName: 'قیچی', emoji: '✂️', color: 'silver' },
    { id: 'sc15', name: 'Glue', persianName: 'چسب', emoji: '🧪', color: 'white' },
    { id: 'sc16', name: 'Pen', persianName: 'خودکار', emoji: '🖊️', color: 'blue' },
    { id: 'sc17', name: 'Computer', persianName: 'کامپیوتر', emoji: '💻', color: 'gray' },
    { id: 'sc18', name: 'Library', persianName: 'کتابخانه', emoji: '📚', color: 'brown' },
    { id: 'sc19', name: 'Bus', persianName: 'سرویس مدرسه', emoji: '🚌', color: 'yellow' },
    { id: 'sc20', name: 'School', persianName: 'مدرسه', emoji: '🏫', color: 'red' }
  ]},
  { id: 'clothes', name: 'Clothes', icon: '👕', color: 'bg-cyan-500', items: [
    { id: 'cl1', name: 'Shirt', persianName: 'پیراهن', emoji: '👕', color: 'blue' },
    { id: 'cl2', name: 'Pants', persianName: 'شلوار', emoji: '👖', color: 'blue' },
    { id: 'cl3', name: 'Dress', persianName: 'لباس زنانه', emoji: '👗', color: 'blue' },
    { id: 'cl4', name: 'Hat', persianName: 'کلاه', emoji: '🎩', color: 'black' },
    { id: 'cl5', name: 'Shoes', persianName: 'کفش', emoji: '👟', color: 'white' },
    { id: 'cl6', name: 'Socks', persianName: 'جوراب', emoji: '🧦', color: 'multi' },
    { id: 'cl7', name: 'Jacket', persianName: 'کاپشن', emoji: '🧥', color: 'brown' },
    { id: 'cl8', name: 'Gloves', persianName: 'دستکش', emoji: '🧤', color: 'green' },
    { id: 'cl9', name: 'Scarf', persianName: 'شال گردن', emoji: '🧣', color: 'red' },
    { id: 'cl10', name: 'Skirt', persianName: 'دامن', emoji: '👗', color: 'pink' },
    { id: 'cl11', name: 'Sweater', persianName: 'پلیور', emoji: '👕', color: 'blue' },
    { id: 'cl12', name: 'Tie', persianName: 'کراوات', emoji: '👔', color: 'blue' },
    { id: 'cl13', name: 'Boots', persianName: 'چکمه', emoji: '🥾', color: 'brown' },
    { id: 'cl14', name: 'Glasses', persianName: 'عینک', emoji: '👓', color: 'black' },
    { id: 'cl15', name: 'Belt', persianName: 'کمربند', emoji: '🎫', color: 'black' },
    { id: 'cl16', name: 'Pajamas', persianName: 'لباس خواب', emoji: '🛌', color: 'blue' },
    { id: 'cl17', name: 'Watch', persianName: 'ساعت مچی', emoji: '⌚', color: 'black' },
    { id: 'cl18', name: 'Raincoat', persianName: 'بارانی', emoji: '🧥', color: 'yellow' },
    { id: 'cl19', name: 'Shorts', persianName: 'شلوارک', emoji: '🩳', color: 'blue' },
    { id: 'cl20', name: 'Slippers', persianName: 'دمپایی', emoji: '🩴', color: 'blue' }
  ]},
  { id: 'house', name: 'House', icon: '🏠', color: 'bg-orange-700', items: [
    { id: 'h1', name: 'Door', persianName: 'درب', emoji: '🚪', color: 'brown' },
    { id: 'h2', name: 'Window', persianName: 'پنجره', emoji: '🪟', color: 'blue' },
    { id: 'h3', name: 'Key', persianName: 'کلید', emoji: '🔑', color: 'yellow' },
    { id: 'h4', name: 'Bed', persianName: 'تخت خواب', emoji: '🛏️', color: 'blue' },
    { id: 'h5', name: 'Table', persianName: 'میز', emoji: '🪑', color: 'brown' },
    { id: 'h6', name: 'Chair', persianName: 'صندلی', emoji: '🪑', color: 'brown' },
    { id: 'h7', name: 'Lamp', persianName: 'لامپ', emoji: '💡', color: 'yellow' },
    { id: 'h8', name: 'Sofa', persianName: 'مبل', emoji: '🛋️', color: 'blue' },
    { id: 'h9', name: 'Fridge', persianName: 'یخچال', emoji: '🧊', color: 'white' },
    { id: 'h10', name: 'Clock', persianName: 'ساعت', emoji: '⏰', color: 'red' },
    { id: 'h11', name: 'Mirror', persianName: 'آینه', emoji: '🪞', color: 'white' },
    { id: 'h12', name: 'Toilet', persianName: 'توالت', emoji: '🚽', color: 'white' },
    { id: 'h13', name: 'Bath', persianName: 'حمام', emoji: '🛀', color: 'white' },
    { id: 'h14', name: 'Soap', persianName: 'صابون', emoji: '🧼', color: 'pink' },
    { id: 'h15', name: 'Towel', persianName: 'حوله', emoji: '🧣', color: 'white' },
    { id: 'h16', name: 'Phone', persianName: 'تلفن', emoji: '☎️', color: 'black' },
    { id: 'h17', name: 'TV', persianName: 'تلویزیون', emoji: '📺', color: 'black' },
    { id: 'h18', name: 'Kitchen', persianName: 'آشپزخانه', emoji: '🍳', color: 'gray' },
    { id: 'h19', name: 'Stairs', persianName: 'پله‌ها', emoji: '🪜', color: 'brown' },
    { id: 'h20', name: 'House', persianName: 'خانه', emoji: '🏠', color: 'red' }
  ]},
  { id: 'family', name: 'Family', icon: '👨‍👩‍👧', color: 'bg-red-500', items: [
    { id: 'fa1', name: 'Father', persianName: 'پدر', emoji: '👨', color: 'human' },
    { id: 'fa2', name: 'Mother', persianName: 'مادر', emoji: '👩', color: 'human' },
    { id: 'fa3', name: 'Brother', persianName: 'برادر', emoji: '👦', color: 'human' },
    { id: 'fa4', name: 'Sister', persianName: 'خواهر', emoji: '👧', color: 'human' },
    { id: 'fa5', name: 'Baby', persianName: 'نوزاد', emoji: '👶', color: 'human' },
    { id: 'fa6', name: 'Grandpa', persianName: 'پدربزرگ', emoji: '👴', color: 'human' },
    { id: 'fa7', name: 'Grandma', persianName: 'مادربزرگ', emoji: '👵', color: 'human' },
    { id: 'fa8', name: 'Uncle', persianName: 'عمو/دایی', emoji: '👨', color: 'human' },
    { id: 'fa9', name: 'Aunt', persianName: 'عمه/خاله', emoji: '👩', color: 'human' },
    { id: 'fa10', name: 'Son', persianName: 'پسر', emoji: '👦', color: 'human' },
    { id: 'fa11', name: 'Daughter', persianName: 'دختر', emoji: '👧', color: 'human' },
    { id: 'fa12', name: 'Friends', persianName: 'دوستان', emoji: '🧑‍🤝‍🧑', color: 'human' },
    { id: 'fa13', name: 'Love', persianName: 'عشق', emoji: '❤️', color: 'red' },
    { id: 'fa14', name: 'Happy Family', persianName: 'خانواده شاد', emoji: '👨‍👩‍👧‍👦', color: 'human' },
    { id: 'fa15', name: 'Boy', persianName: 'پسر بچه', emoji: '👦', color: 'human' },
    { id: 'fa16', name: 'Girl', persianName: 'دختر بچه', emoji: '👧', color: 'human' },
    { id: 'fa17', name: 'Man', persianName: 'مرد', emoji: '👨', color: 'human' },
    { id: 'fa18', name: 'Woman', persianName: 'زن', emoji: '👩', color: 'human' },
    { id: 'fa19', name: 'Home', persianName: 'خانه', emoji: '🏠', color: 'red' },
    { id: 'fa20', name: 'Kiss', persianName: 'بوسه', emoji: '😘', color: 'red' }
  ]},
  { id: 'emotions', name: 'Emotions', icon: '😊', color: 'bg-yellow-400', items: [
    { id: 'e1', name: 'Happy', persianName: 'خوشحال', emoji: '😊', color: 'yellow' },
    { id: 'e2', name: 'Sad', persianName: 'غمگین', emoji: '😢', color: 'blue' },
    { id: 'e3', name: 'Angry', persianName: 'عصبانی', emoji: '😠', color: 'red' },
    { id: 'e4', name: 'Scared', persianName: 'ترسیده', emoji: '😨', color: 'purple' },
    { id: 'e5', name: 'Surprised', persianName: 'متعجب', emoji: '😮', color: 'yellow' },
    { id: 'e6', name: 'Sleepy', persianName: 'خواب‌آلود', emoji: '😴', color: 'blue' },
    { id: 'e7', name: 'Silly', persianName: 'احمقانه', emoji: '😜', color: 'yellow' },
    { id: 'e8', name: 'Shy', persianName: 'خجالتی', emoji: '😊', color: 'pink' },
    { id: 'e9', name: 'Loved', persianName: 'محبوب', emoji: '🥰', color: 'red' },
    { id: 'e10', name: 'Tired', persianName: 'خسته', emoji: '😫', color: 'gray' },
    { id: 'e11', name: 'Bored', persianName: 'بی‌حوصله', emoji: '😑', color: 'gray' },
    { id: 'e12', name: 'Proud', persianName: 'مفتخر', emoji: '😎', color: 'yellow' },
    { id: 'e13', name: 'Nervous', persianName: 'نگران', emoji: '😟', color: 'blue' },
    { id: 'e14', name: 'Confused', persianName: 'گیج', emoji: '😕', color: 'gray' },
    { id: 'e15', name: 'Cool', persianName: 'باحال', emoji: '😎', color: 'yellow' },
    { id: 'e16', name: 'Hungry', persianName: 'گرسنه', emoji: '🤤', color: 'yellow' },
    { id: 'e17', name: 'Thirsty', persianName: 'تشنه', emoji: '💧', color: 'blue' },
    { id: 'e18', name: 'Strong', persianName: 'قوی', emoji: '💪', color: 'peach' },
    { id: 'e19', name: 'Laughing', persianName: 'خندان', emoji: '🤣', color: 'yellow' },
    { id: 'e20', name: 'Kiss', persianName: 'بوسه', emoji: '😘', color: 'red' }
  ]},
  { id: 'sports', name: 'Sports', icon: '🏆', color: 'bg-emerald-500', items: [
    { id: 'sp1', name: 'Soccer', persianName: 'فوتبال', emoji: '⚽', color: 'white' },
    { id: 'sp2', name: 'Basketball', persianName: 'بسکتبال', emoji: '🏀', color: 'orange' },
    { id: 'sp3', name: 'Tennis', persianName: 'تنیس', emoji: '🎾', color: 'green' },
    { id: 'sp4', name: 'Swimming', persianName: 'شنا', emoji: '🏊', color: 'blue' },
    { id: 'sp5', name: 'Running', persianName: 'دویدن', emoji: '🏃', color: 'peach' },
    { id: 'sp6', name: 'Baseball', persianName: 'بیس‌بال', emoji: '⚾', color: 'white' },
    { id: 'sp7', name: 'Cycling', persianName: 'دوچرخه‌سواری', emoji: '🚲', color: 'blue' },
    { id: 'sp8', name: 'Boxing', persianName: 'بوکس', emoji: '🥊', color: 'red' },
    { id: 'sp9', name: 'Yoga', persianName: 'یوگا', emoji: '🧘', color: 'peach' },
    { id: 'sp10', name: 'Golf', persianName: 'گلف', emoji: '⛳', color: 'green' },
    { id: 'sp11', name: 'Ice Skating', persianName: 'اسکیت روی یخ', emoji: '⛸️', color: 'white' },
    { id: 'sp12', name: 'Winner', persianName: 'برنده', emoji: '🏆', color: 'gold' },
    { id: 'sp13', name: 'Medal', persianName: 'مدال', emoji: '🥇', color: 'gold' },
    { id: 'sp14', name: 'Ball', persianName: 'توپ', emoji: '🏀', color: 'orange' },
    { id: 'sp15', name: 'Helmet', persianName: 'کلاه ایمنی', emoji: '🪖', color: 'green' },
    { id: 'sp16', name: 'Bowling', persianName: 'بولینگ', emoji: '🎳', color: 'red' },
    { id: 'sp17', name: 'Fishing', persianName: 'ماهیگیری', emoji: '🎣', color: 'blue' },
    { id: 'sp18', name: 'Skating', persianName: 'اسکیت', emoji: '🛼', color: 'pink' },
    { id: 'sp19', name: 'Team', persianName: 'تیم', emoji: '🧑‍🤝‍🧑', color: 'human' },
    { id: 'sp20', name: 'Jump', persianName: 'پرش', emoji: '🦘', color: 'brown' }
  ]},
  { id: 'music', name: 'Music', icon: '🎸', color: 'bg-violet-500', items: [
    { id: 'm1', name: 'Guitar', persianName: 'گیتار', emoji: '🎸', color: 'brown' },
    { id: 'm2', name: 'Piano', persianName: 'پیانو', emoji: '🎹', color: 'black' },
    { id: 'm3', name: 'Drum', persianName: 'طبل', emoji: '🥁', color: 'red' },
    { id: 'm4', name: 'Violin', persianName: 'ویولن', emoji: '🎻', color: 'brown' },
    { id: 'm5', name: 'Trumpet', persianName: 'شیپور', emoji: '🎺', color: 'gold' },
    { id: 'm6', name: 'Singing', persianName: 'آواز', emoji: '🎤', color: 'gray' },
    { id: 'm7', name: 'Headphones', persianName: 'هدفون', emoji: '🎧', color: 'black' },
    { id: 'm8', name: 'Note', persianName: 'نت موسیقی', emoji: '🎵', color: 'black' },
    { id: 'm9', name: 'CD', persianName: 'سی‌دی', emoji: '💿', color: 'silver' },
    { id: 'm10', name: 'Radio', persianName: 'رادیو', emoji: '📻', color: 'brown' },
    { id: 'm11', name: 'Dance', persianName: 'رقص', emoji: '💃', color: 'red' },
    { id: 'm12', name: 'Saxophone', persianName: 'ساکسیفون', emoji: '🎷', color: 'gold' },
    { id: 'm13', name: 'Harp', persianName: 'چنگ', emoji: '🪕', color: 'brown' },
    { id: 'm14', name: 'Microphone', persianName: 'میکروفون', emoji: '🎙️', color: 'gray' },
    { id: 'm15', name: 'Speaker', persianName: 'بلندگو', emoji: '📢', color: 'red' },
    { id: 'm16', name: 'Bell', persianName: 'زنگوله', emoji: '🔔', color: 'gold' },
    { id: 'm17', name: 'Stage', persianName: 'سن', emoji: '🎭', color: 'purple' },
    { id: 'm18', name: 'Music Box', persianName: 'جعبه موسیقی', emoji: '📻', color: 'brown' },
    { id: 'm19', name: 'Band', persianName: 'گروه موسیقی', emoji: '🧑‍🎤', color: 'multi' },
    { id: 'm20', name: 'Applause', persianName: 'تشویق', emoji: '👏', color: 'human' }
  ]},
  { id: 'sea', name: 'Sea', icon: '🐳', color: 'bg-blue-600', items: [
    { id: 'se1', name: 'Fish', persianName: 'ماهی', emoji: '🐟', color: 'blue' },
    { id: 'se2', name: 'Whale', persianName: 'نهنگ', emoji: '🐳', color: 'blue' },
    { id: 'se3', name: 'Dolphin', persianName: 'دلفین', emoji: '🐬', color: 'blue' },
    { id: 'se4', name: 'Shark', persianName: 'کوسه', emoji: '🦈', color: 'gray' },
    { id: 'se5', name: 'Octopus', persianName: 'هشت‌پا', emoji: '🐙', color: 'pink' },
    { id: 'se6', name: 'Crab', persianName: 'خرچنگ', emoji: '🦀', color: 'red' },
    { id: 'se7', name: 'Turtle', persianName: 'لاک‌پشت', emoji: '🐢', color: 'green' },
    { id: 'se8', name: 'Starfish', persianName: 'ستاره دریایی', emoji: '⭐', color: 'orange' },
    { id: 'se9', name: 'Shell', persianName: 'صدف', emoji: '🐚', color: 'white' },
    { id: 'se10', name: 'Seaweed', persianName: 'جلبک', emoji: '🌿', color: 'green' },
    { id: 'se11', name: 'Ship', persianName: 'کشتی', emoji: '🚢', color: 'blue' },
    { id: 'se12', name: 'Island', persianName: 'جزیره', emoji: '🏝️', color: 'green' },
    { id: 'se13', name: 'Sand', persianName: 'شن', emoji: '🏖️', color: 'yellow' },
    { id: 'se14', name: 'Wave', persianName: 'موج', emoji: '🌊', color: 'blue' },
    { id: 'se15', name: 'Submarine', persianName: 'زیردریایی', emoji: '🚤', color: 'yellow' },
    { id: 'se16', name: 'Anchor', persianName: 'لنگر', emoji: '⚓', color: 'gray' },
    { id: 'se17', name: 'Seahorse', persianName: 'اسب دریایی', emoji: '🐴', color: 'orange' },
    { id: 'se18', name: 'Jellyfish', persianName: 'عروس دریایی', emoji: '🎐', color: 'pink' },
    { id: 'se19', name: 'Treasure', persianName: 'گنج', emoji: '💎', color: 'gold' },
    { id: 'se20', name: 'Beach', persianName: 'ساحل', emoji: '⛱️', color: 'yellow' }
  ]},
  { id: 'birds', name: 'Birds', icon: '🦜', color: 'bg-lime-500', items: [
    { id: 'bi1', name: 'Parrot', persianName: 'طوطی', emoji: '🦜', color: 'multi' },
    { id: 'bi2', name: 'Duck', persianName: 'اردک', emoji: '🦆', color: 'yellow' },
    { id: 'bi3', name: 'Owl', persianName: 'جغد', emoji: '🦉', color: 'brown' },
    { id: 'bi4', name: 'Eagle', persianName: 'عقاب', emoji: '🦅', color: 'brown' },
    { id: 'bi5', name: 'Penguin', persianName: 'پنگوئن', emoji: '🐧', color: 'black' },
    { id: 'bi6', name: 'Chicken', persianName: 'جوجه', emoji: '🐤', color: 'yellow' },
    { id: 'bi7', name: 'Flamingo', persianName: 'فلامینگو', emoji: '🦩', color: 'pink' },
    { id: 'bi8', name: 'Peacock', persianName: 'طاووس', emoji: '🦚', color: 'blue' },
    { id: 'bi9', name: 'Swan', persianName: 'قو', emoji: '🦢', color: 'white' },
    { id: 'bi10', name: 'Crow', persianName: 'کلاغ', emoji: '🐦', color: 'black' },
    { id: 'bi11', name: 'Dove', persianName: 'کبوتر', emoji: '🕊️', color: 'white' },
    { id: 'bi12', name: 'Egg', persianName: 'تخم‌مرغ', emoji: '🥚', color: 'white' },
    { id: 'bi13', name: 'Nest', persianName: 'لانه', emoji: '🪺', color: 'brown' },
    { id: 'bi14', name: 'Feather', persianName: 'پر', emoji: '🪶', color: 'gray' },
    { id: 'bi15', name: 'Wing', persianName: 'بال', emoji: '💸', color: 'gray' },
    { id: 'bi16', name: 'Fly', persianName: 'پرواز', emoji: '🪁', color: 'blue' },
    { id: 'bi17', name: 'Turkey', persianName: 'بوقلمون', emoji: '🦃', color: 'brown' },
    { id: 'bi18', name: 'Rooster', persianName: 'خروس', emoji: '🐓', color: 'red' },
    { id: 'bi19', name: 'Hen', persianName: 'مرغ', emoji: '🐔', color: 'white' },
    { id: 'bi20', name: 'Birdhouse', persianName: 'خانه پرنده', emoji: '🏘️', color: 'brown' }
  ]},
  { id: 'insects', name: 'Insects', icon: '🦋', color: 'bg-amber-400', items: [
    { id: 'in1', name: 'Butterfly', persianName: 'پروانه', emoji: '🦋', color: 'blue' },
    { id: 'in2', name: 'Bee', persianName: 'زنبور', emoji: '🐝', color: 'yellow' },
    { id: 'in3', name: 'Ladybug', persianName: 'کفشدوزک', emoji: '🐞', color: 'red' },
    { id: 'in4', name: 'Ant', persianName: 'مورچه', emoji: '🐜', color: 'brown' },
    { id: 'in5', name: 'Spider', persianName: 'عنکبوت', emoji: '🕷️', color: 'black' },
    { id: 'in6', name: 'Fly', persianName: 'مگس', emoji: '🪰', color: 'black' },
    { id: 'in7', name: 'Snail', persianName: 'حلزون', emoji: '🐌', color: 'brown' },
    { id: 'in8', name: 'Caterpillar', persianName: 'کرم ابریشم', emoji: '🐛', color: 'green' },
    { id: 'in9', name: 'Honey', persianName: 'عسل', emoji: '🍯', color: 'yellow' },
    { id: 'in10', name: 'Web', persianName: 'تار', emoji: '🕸️', color: 'gray' },
    { id: 'in11', name: 'Grasshopper', persianName: 'ملخ', emoji: '🦗', color: 'green' },
    { id: 'in12', name: 'Cricket', persianName: 'جیرجیرک', emoji: '🦗', color: 'brown' },
    { id: 'in13', name: 'Scorpion', persianName: 'عقرب', emoji: '🦂', color: 'brown' },
    { id: 'in14', name: 'Mosquito', persianName: 'پشه', emoji: '🦟', color: 'black' },
    { id: 'in15', name: 'Dragonfly', persianName: 'سنجاقک', emoji: '🪁', color: 'blue' },
    { id: 'in16', name: 'Flower', persianName: 'گل', emoji: '🌸', color: 'pink' },
    { id: 'in17', name: 'Leaf', persianName: 'برگ', emoji: '🍃', color: 'green' },
    { id: 'in18', name: 'Garden', persianName: 'باغچه', emoji: '🏡', color: 'green' },
    { id: 'in19', name: 'Sun', persianName: 'آفتاب', emoji: '☀️', color: 'yellow' },
    { id: 'in20', name: 'Colors', persianName: 'رنگ‌ها', emoji: '🎨', color: 'multi' }
  ]},
  { id: 'vegetables', name: 'Vegetables', icon: 'broccoli', color: 'bg-green-700', items: [
    { id: 'vg1', name: 'Carrot', persianName: 'هویج', emoji: '🥕', color: 'orange' },
    { id: 'vg2', name: 'Broccoli', persianName: 'بروکلی', emoji: '🥦', color: 'green' },
    { id: 'vg3', name: 'Corn', persianName: 'ذرت', emoji: '🌽', color: 'yellow' },
    { id: 'vg4', name: 'Tomato', persianName: 'گوجه‌فرنگی', emoji: '🍅', color: 'red' },
    { id: 'vg5', name: 'Potato', persianName: 'سیب‌زمینی', emoji: '🥔', color: 'brown' },
    { id: 'vg6', name: 'Onion', persianName: 'پیاز', emoji: '🧅', color: 'white' },
    { id: 'vg7', name: 'Cucumber', persianName: 'خیار', emoji: '🥒', color: 'green' },
    { id: 'vg8', name: 'Eggplant', persianName: 'بادمجان', emoji: '🍆', color: 'purple' },
    { id: 'vg9', name: 'Mushroom', persianName: 'قارچ', emoji: '🍄', color: 'red' },
    { id: 'vg10', name: 'Garlic', persianName: 'سیر', emoji: '🧄', color: 'white' },
    { id: 'vg11', name: 'Peas', persianName: 'نخود فرنگی', emoji: '🫛', color: 'green' },
    { id: 'vg12', name: 'Pepper', persianName: 'فلفل دلمه‌ای', emoji: '🫑', color: 'green' },
    { id: 'vg13', name: 'Cabbage', persianName: 'کلم', emoji: '🥬', color: 'green' },
    { id: 'vg14', name: 'Salad', persianName: 'سالاد', emoji: '🥗', color: 'green' },
    { id: 'vg15', name: 'Pumpkin', persianName: 'کدو تنبل', emoji: '🎃', color: 'orange' },
    { id: 'vg16', name: 'Hot Pepper', persianName: 'فلفل تند', emoji: '🌶️', color: 'red' },
    { id: 'vg17', name: 'Olive', persianName: 'زیتون', emoji: '🫒', color: 'green' },
    { id: 'vg18', name: 'Lettuce', persianName: 'کاهو', emoji: '🥬', color: 'green' },
    { id: 'vg19', name: 'Radish', persianName: 'تربچه', emoji: '🍎', color: 'red' },
    { id: 'vg20', name: 'Soup', persianName: 'سوپ', emoji: '🍲', color: 'orange' }
  ]},
  { id: 'actions', name: 'Actions', icon: '🏃', color: 'bg-orange-600', items: [
    { id: 'ac1', name: 'Run', persianName: 'دویدن', emoji: '🏃', color: 'human' },
    { id: 'ac2', name: 'Jump', persianName: 'پریدن', emoji: '🦘', color: 'brown' },
    { id: 'ac3', name: 'Walk', persianName: 'راه رفتن', emoji: '🚶', color: 'human' },
    { id: 'ac4', name: 'Sleep', persianName: 'خوابیدن', emoji: '😴', color: 'blue' },
    { id: 'ac5', name: 'Eat', persianName: 'خوردن', emoji: '😋', color: 'human' },
    { id: 'ac6', name: 'Drink', persianName: 'نوشیدن', emoji: '🥤', color: 'blue' },
    { id: 'ac7', name: 'Read', persianName: 'خواندن', emoji: '📖', color: 'red' },
    { id: 'ac8', name: 'Write', persianName: 'نوشتن', emoji: '✍️', color: 'human' },
    { id: 'ac9', name: 'Sing', persianName: 'آواز خواندن', emoji: '🎤', color: 'gray' },
    { id: 'ac10', name: 'Dance', persianName: 'رقصیدن', emoji: '💃', color: 'red' },
    { id: 'ac11', name: 'Play', persianName: 'بازی کردن', emoji: '🎮', color: 'black' },
    { id: 'ac12', name: 'Laugh', persianName: 'خندیدن', emoji: '😂', color: 'yellow' },
    { id: 'ac13', name: 'Cry', persianName: 'گریه کردن', emoji: '😢', color: 'blue' },
    { id: 'ac14', name: 'Think', persianName: 'فکر کردن', emoji: '🤔', color: 'yellow' },
    { id: 'ac15', name: 'Swim', persianName: 'شنا کردن', emoji: '🏊', color: 'blue' },
    { id: 'ac16', name: 'Fly', persianName: 'پرواز کردن', emoji: '🪁', color: 'blue' },
    { id: 'ac17', name: 'Climb', persianName: 'بالا رفتن', emoji: '🧗', color: 'human' },
    { id: 'ac18', name: 'Clean', persianName: 'تمیز کردن', emoji: '🧹', color: 'brown' },
    { id: 'ac19', name: 'Wash', persianName: 'شستن', emoji: '🧼', color: 'blue' },
    { id: 'ac20', name: 'Smile', persianName: 'لبخند زدن', emoji: '😊', color: 'yellow' }
  ]},
  { id: 'shapes', name: 'Shapes', icon: '📐', color: 'bg-pink-400', items: [
    { id: 'sh1', name: 'Star', persianName: 'ستاره', emoji: '⭐', color: 'yellow' },
    { id: 'sh2', name: 'Circle', persianName: 'دایره', emoji: '🔴', color: 'red' },
    { id: 'sh3', name: 'Square', persianName: 'مربع', emoji: '🟦', color: 'blue' },
    { id: 'sh4', name: 'Triangle', persianName: 'مثلث', emoji: '📐', color: 'silver' },
    { id: 'sh5', name: 'Heart', persianName: 'قلب', emoji: '❤️', color: 'red' },
    { id: 'sh6', name: 'Diamond', persianName: 'لوزی', emoji: '💎', color: 'cyan' },
    { id: 'sh7', name: 'Moon', persianName: 'ماه', emoji: '🌙', color: 'yellow' },
    { id: 'sh8', name: 'Dot', persianName: 'نقطه', emoji: '⏺️', color: 'black' },
    { id: 'sh9', name: 'Cross', persianName: 'صلیب', emoji: '➕', color: 'red' },
    { id: 'sh10', name: 'Arrow', persianName: 'فلش', emoji: '➡️', color: 'blue' },
    { id: 'sh11', name: 'Line', persianName: 'خط', emoji: '➖', color: 'black' },
    { id: 'sh12', name: 'Spiral', persianName: 'مارپیچ', emoji: '🌀', color: 'blue' },
    { id: 'sh13', name: 'Box', persianName: 'جعبه', emoji: '📦', color: 'brown' },
    { id: 'sh14', name: 'Ball', persianName: 'کره', emoji: '⚽', color: 'white' },
    { id: 'sh15', name: 'Ring', persianName: 'حلقه', emoji: '💍', color: 'gold' },
    { id: 'sh16', name: 'Oval', persianName: 'بیضی', emoji: '🥚', color: 'white' },
    { id: 'sh17', name: 'Cloud', persianName: 'ابر', emoji: '☁️', color: 'gray' },
    { id: 'sh18', name: 'Flash', persianName: 'صاعقه', emoji: '⚡', color: 'yellow' },
    { id: 'sh19', name: 'Flower', persianName: 'گل', emoji: '🌸', color: 'pink' },
    { id: 'sh20', name: 'Cylinder', persianName: 'استوانه', emoji: '🥫', color: 'silver' }
  ]}
];
